### ISSUE TITLE
Critique

### ISSUE THREAD

**Issue by nathansquire67** [deco3500/TheLocalCode#2]
I like the idea of a virtual noticeboard, although I think it would be awkward to interact with. Maybe the setup could be split into two parts, the website where students and teachers can send posts and have discussions, and then the actual virtual noticeboard which displays the information but can’t be interacted with.

**Comment by davo27** [comment]
We agree, interacting with this notice board could be awkward for N number of students and 1 notice board. It would be good to have it how you suggested since it would make the interactions less awkward. Our only concern is that it might actually take away from the physical space and make the big displays less important (think of how much the displays at UQ are actually used by people). 

Thanks for the feedback :)
