### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by clandan** [deco3500/TheLocalCode#5]
Sounds like a live feed notice board. How will your idea be functionally different from a simple facebook page that the school runs?  Will posts need approval before they are visible to other users? Will the student-centric section be separate from the school endorsed one?

**Comment by davo27** [comment]
1. Hopefully the difference between our idea of a notice board and Facebook's would be the school has greater control over the content. This would help address privacy concerns along with bullying etc. Ideally our design would make news "stand out" faster and get the point across faster (almost like a collection of post-it note but with more detail).
2. So posts will need to be approved before going out to the rest of the system (likely by teachers for example).
3. We wanted the two to be merged together to help make news more general rather than broken up into sections (if it wasn't i would imagine students would just ignore the schools side of the board right?).

Thank you for the feedback :)
