### ISSUE TITLE
Critique

### ISSUE THREAD

**Issue by rebeccarebeccali** [deco3500/TheLocalCode#7]
Great idea combining Facebook and Blackboard functions into an app. Similar to the previous feedback given by the others, some of my concerns are:
How to control inappropriate posts?
Privacy issues for the students.
If the students know that their posts/comments can be viewed by their teachers / parents, I don't think it will be so attractive for the students to use the app.

**Comment by davo27** [comment]
Hi, thanks for the feedback.
- so inappropriate posts should be picked out by teaching staff as all posts need to run through them before being circulated out to the rest of the school.
- Since all these posts run through staff they should address any privacy concerns relating to the posts.
- We are thinking of removing the parent aspect of view student posts. But teachers would need to hang around as they are acting as filters and moderators. This is a issue we need to look into as it will effect the effectiveness of the idea.

Thank you for the feedback :)
